// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportBook(arg1:string):Promise<void>;

export function GetSystemFonts():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListBooks():Promise<Array<string>>;

export function LoadData():Promise<main.AppData>;

export function LoadSettings():Promise<main.AppSettings>;

export function NewBook(arg1:string):Promise<void>;

export function ResetData():Promise<void>;

export function SaveData(arg1:main.AppData):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SwitchBook(arg1:string):Promise<void>;
