// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBook(arg1) {
  return window['go']['main']['App']['ExportBook'](arg1);
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListBooks() {
  return window['go']['main']['App']['ListBooks']();
}

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function NewBook(arg1) {
  return window['go']['main']['App']['NewBook'](arg1);
}

export function ResetData() {
  return window['go']['main']['App']['ResetData']();
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SwitchBook(arg1) {
  return window['go']['main']['App']['SwitchBook'](arg1);
}
